### PR TITLE
Radar Update

### PR DESCRIPTION
**Pull request by Souper07**
+DX11 Support
+New collision box
+Construction stages

### CODE REVIEW

**Comment by Rynchodon** [comment]
Some minor issues:
* Is it possible/easy to add the collision box to the construction stages? I tried and failed miserably.
* The model is flipped (now faces the opposite direction). Is it easy to change it?
* The mount point is now the entire bottom, was this intentional?

**Comment by Souper07** [comment]
I did not think to test the collision box on the construction stages....do they not have one? When your fbx into blender it places it in the center so I picked a corner to place it in. That can easily be changed. It just needs to go in the opposite corner, correct? The entire bottom is a mount point was intentional, but is it causing any issues?

**Comment by Rynchodon** [comment]
>I did not think to test the collision box on the construction stages....do they not have one? I don't think there is a way I can have custom collision boxes for the construction stages.

I just noticed because I was grinding it down to see the construction stages and it pushed me away.

>When I put your fbx into blender it places it in the center so I picked a corner to place it in. That can easily be changed. It just needs to go in the opposite corner, correct?

I think that will work, thank you.

>The entire bottom is a mount point was intentional, but is it causing any issues?

Nope, just seems odd.

**Comment by Rynchodon** [comment]
I figured out the collision thing, needed to make copies of both the .hkt and .hkt.fbx files.

**Comment by Souper07** [comment]
Might have to re-do some of that when I put up the rotated model. All of the collision boxes will have to be rotated too. I should have time tomorrow to get this done.

**Comment by Souper07** [comment]
Try that.

**Comment by Rynchodon** [comment]
The model now faces the correct direction but the .hkt does not:

2015-07-25-14-44-58-799_finalscreen

**Comment by Souper07** [comment]
capture

**Comment by Souper07** [comment]
In-game result.

**Pull request merged**
