### PR TITLE
Radar Update

### PR DESCRIPTION
**Pull request by Souper07**
+Moved position, can mount on rotor.
+New Textures.
+New Construction Stages.
+Collision box, smaller than before.

### CODE REVIEW

**Comment by zrisher** [comment]
Same look as in #61 right?

**Comment by Souper07** [comment]
Only thing different is the file structure was left alone.

**Comment by Rynchodon** [comment]
The problem is not with the file structure. Moving the mount points can prevent existing radar from being placed. 
I think what I'll have to do is include this as a new block and hide the old one from the G-menu.

**Comment by Souper07** [comment]
The only real benefit from moving the model was so it could be put on a rotor, and that adds 0 functionality so maybe it's best to just leave it how it was.

**Comment by Rynchodon** [comment]
I wish I had never stuck a radar on a rotor in the first place... I could instead just put blueprints on the workshop of a radar on a rotor.

**Pull request closed without merging**
