### PR TITLE
Radar Update

### PR DESCRIPTION
**Pull request by Souper07**
+ Retextured.
+ Custom collision box, takes up less physical space.
+ 3 new construction stages.
+ Shifted model position/mount point, can now mount directly onto rotor
block.
+ Smoothed out edges of dish shape.
+ File structure changes to make AntennaRelay folder match Autopilot
folder.

### CODE REVIEW

**Comment by zrisher** [comment]
Nice! Wish we could get rid of that beacon light effect, but I know that's a challenge.

Do you think in the future it might make sense to do the rotation of this in the block itself, kind of like turret idle rotation?

**Comment by Rynchodon** [comment]
>Nice! Wish we could get rid of that beacon light effect, but I know that's a challenge.

The light effect is hard coded, even stopping all of the beacon updates does nothing.

>Do you think in the future it might make sense to do the rotation of this in the block itself, kind of like turret idle rotation?

Custom blocks cannot be added to Space Engineers, it has to be derived from an existing block.

**Comment by zrisher** [comment]
> The light effect is hard coded, even stopping all of the beacon updates does nothing.

Right, that's why this would be a bit of a challenge. It would be a fairly small PR into core to make this configurable via ModAPI, though.

> Custom blocks cannot be added to Space Engineers, it has to be derived from an existing block.

Right, I was thinking we could model it as a turret instead of a beacon, but we need the Radius from block definition/control-panel config, and there's no way to change the available menu items available. That would definitely be a bigger challenge to add to Core, though I'd love for custom blocks to eventually be available. : /

**Comment by Souper07** [comment]
Is there something wrong with this PR?

**Comment by Rynchodon** [comment]
>Is there something wrong with this PR?

It kinda messes up existing Radar and I have not found a solution.
Also, I'm not seeing any custom collision box, still just a cube.

**Comment by Souper07** [comment]
I will retry later but I'll leave the file structure the same and name it to match the old files exactly.

**Pull request closed without merging**
