### PR TITLE
release 24

### PR DESCRIPTION
**Pull request by Rynchodon**

### CODE REVIEW

**Comment by zrisher** [comment]
+disable reverse thrusters, instead of dampeners, when cruising forward
+dumb turrets are now disabled if there are no possible targets
+react when default targeting acquires unowned block on friendly ship
+bug fix for turrets' nearby enemies test
+made block communication script for filtering simpler to use
+added current time to detected grid display
+when displayed information is old, the background will turn Gray

Looks like some good stuff! So Smart Turrets now does turret management entirely for us.

**Comment by Rynchodon** [comment]
Almost, there are two cases where turrets will not turn off:
* Target Characters is enabled
* Target Meteors is enabled and word is hostile

**Comment by zrisher** [comment]
For characters, is it difficult to detect their presence?
For meteors, makes sense, is there any way to hook in to the event occurrence?

Asking just out of curiosity.

**Comment by Rynchodon** [comment]
It would be relatively simple, though not very efficient, to add a simple test for characters or meteors nearby. Instead, I am working on a solution that integrates characters and meteors into antenna relay, it is taking longer than I thought it would (& I keep getting sidetracked by everything else I really want to fix).

**Comment by zrisher** [comment]
Ok, wish I knew more about the architecture to discuss that but sounds good. I know how it is to get sidetracked! You do great work though.

**Pull request merged**
