### PR TITLE
Phased Array block

### PR DESCRIPTION
**Pull request by Souper07**
All done.

### CODE REVIEW

**Comment by zrisher** [comment]
Looks cool!

**Comment by Rynchodon** [comment]
Would you mind uploading the xml files?

**Comment by Souper07** [comment]
Oh sure.

**Comment by Rynchodon** [comment]
Slight problem with DX9

2015-10-03-10-53-14-790_finalscreen

**Comment by Souper07** [comment]
interesting

**Comment by Souper07** [comment]
I'm having the same problem with another MOD. Looks fine in dX11 but the faces seem uv mapped differently in dX11. No clue why.

**Pull request merged**
