### PR TITLE
release 23

### PR DESCRIPTION
**Pull request by Rynchodon**

### CODE REVIEW

**Comment by zrisher** [comment]
Nice! Excited to try out some of this.

I think if I were to make a video demonstrating a defensive ship-to-ship missile platform that makes use of the radar programmable block work, put it on the reddit, that would pique some interest.

**Comment by Rynchodon** [comment]
Let me know if I can help.

**Comment by zrisher** [comment]
@Rynchodon could you release (or just send me) the world you used for the screenshots in this
http://steamcommunity.com/sharedfiles/filedetails/?id=391453613 as a starting point?

**Comment by Rynchodon** [comment]
Here is the world you requested:
http://steamcommunity.com/sharedfiles/filedetails/?id=424988459

I do not think that there is much there that would be helpful. I could email you some other worlds, or add them to git.

**Pull request merged**
