### PR TITLE
models & textures paths

### PR DESCRIPTION
**Pull request by Rynchodon**
changed paths so that models and textures in source now parallel mods
folder

### CODE REVIEW

**Comment by Souper07** [comment]
Can the build script also be changed to place icons into textures\icons? That is the default folder that the Blender config updates it to be when I make a model.

**Comment by Rynchodon** [comment]
>Thank you. That drove me crazy.

See I'm already crazy, so it made perfect sense to me.

>Can the build script also be changed to place icons into textures\icons? That is the default folder that the Blender config updates it to be when I make a model.

I'll add that as an alternate option.

**Comment by Rynchodon** [comment]
Does the blender tool have other unconventional output directories?

**Comment by Souper07** [comment]
Other than the large\small folders, no. I figured out how to have to put small/large blocks into small/large folder but it still doesn't update the .sbc file to look there. It always just asumes both block sizes are in the same folder. So what I do is just work from the mods folder then when I am ready to make a commit I drag over the necessary files and change the .sbc file to match the github file structure.

**Comment by Rynchodon** [comment]
What about textures? I saw that they were in Textures\Cubes, is the plugin putting them there?

**Comment by Souper07** [comment]
I put those there when I first make a block. Usually I do textures\models\cubes but it's not critical.

**Comment by Rynchodon** [comment]
#71 Should make things simple, as long as the .sbc and .xml files point to the models & textures, build should be able to find them. It will also complain about bad paths so the game does not have to be loaded to check.

**Comment by Souper07** [comment]
Awesome. Thank you. I might actually work from the github folder now.

**Pull request merged**
