### PR TITLE
fix for new block definition reqs 1.010.020

### PR DESCRIPTION
**Pull request by zrisher**
Tested and working locally

### CODE REVIEW

**Comment by Rynchodon** [comment]
Well this is awkward.

**Comment by zrisher** [comment]
You missed fixing the indent on line 5 of Radar-Model-A.sbc :p

**Comment by Rynchodon** [comment]
>You missed fixing the indent on line 5 of Radar-Model-A.sbc :p

You mean line 7 of Radar.sbc

**Comment by zrisher** [comment]
Indeed.

**Pull request closed without merging**
