### PR TITLE
Compile fix.

### LINKED ISSUE #57: Instance Reference Error
```
2015-06-21 03:06:55.823 - Thread:   1 ->     MOD_ERROR: 363880940.sbm_Autopilot
2015-06-21 03:06:55.823 - Thread:   1 ->       in file: 363880940.sbm_Autopilot
2015-06-21 03:06:55.823 - Thread:   1 ->       Compilation of 363880940.sbm_Autopilot failed:
2015-06-21 03:06:55.823 - Thread:   1 ->        MOD_ERROR: 363880940.sbm_Autopilot
2015-06-21 03:06:55.823 - Thread:   1 ->          in file: 363880940.sbm_Autopilot
2015-06-21 03:06:55.823 - Thread:   1 ->          c:\Users\Rob\AppData\Local\Temp\355lacp0.9.cs(72,4) : error CS0176: Member 'Rynchodon.Logger.debugNotify(string, int, Rynchodon.Logger.severity)' cannot be accessed with an instance reference; qualify it with a type name instead
```

This results in the autopilot block just sitting there, dead as a doorknob.

```
2015-06-21 03:05:22.956 - Thread:   1 ->  App Version: 01_087_007
2015-06-21 03:05:22.956 - Thread:   1 ->  Steam build: Always true
2015-06-21 03:05:22.956 - Thread:   1 ->  Is official: True [NO][IS][NAMP]
2015-06-21 03:05:22.956 - Thread:   1 ->  Environment.ProcessorCount: 8
2015-06-21 03:05:22.956 - Thread:   1 ->  Environment.OSVersion: Microsoft Windows NT 6.1.7601 Service Pack 1
2015-06-21 03:05:22.956 - Thread:   1 ->  Environment.CommandLine: "F:\SteamLibrary\steamapps\common\SpaceEngineers\Bin64\SpaceEngineers.exe"
2015-06-21 03:05:22.956 - Thread:   1 ->  Environment.Is64BitProcess: True
2015-06-21 03:05:22.956 - Thread:   1 ->  Environment.Is64BitOperatingSystem: True
2015-06-21 03:05:22.956 - Thread:   1 ->  Environment.Version: 4.0.30319.34209
2015-06-21 03:05:22.956 - Thread:   1 ->  Environment.CurrentDirectory: F:\SteamLibrary\steamapps\common\SpaceEngineers\Bin64
2015-06-21 03:05:22.956 - Thread:   1 ->  MainAssembly.ProcessorArchitecture: Amd64
2015-06-21 03:05:22.956 - Thread:   1 ->  ExecutingAssembly.ProcessorArchitecture: Amd64
2015-06-21 03:05:22.956 - Thread:   1 ->  IntPtr.Size: 8
2015-06-21 03:05:22.956 - Thread:   1 ->  Default Culture: en-US
2015-06-21 03:05:22.956 - Thread:   1 ->  Default UI Culture: en-US
2015-06-21 03:05:22.957 - Thread:   1 ->  IsAdmin: False
```

### PR DESCRIPTION
**Pull request by N3X15**
Tested locally, runs fine now.

Fixes #57.

### CODE REVIEW

**Comment by zrisher** [comment]
Rynnnnnch, did you not try out your final build before publishing? : )

**Comment by Rynchodon** [comment]
>Rynnnnnch, did you not try out your final build before publishing? : )
Oh course I did, then I decided I really needed to change something that couldn't possibly break the mod...(and was really super important too...)

**Comment by Rynchodon** [comment]
>Rynnnnnch, did you not try out your final build before publishing? : )

Of course I did, then I did something stupid...

**Comment by Rynchodon** [comment]
>Rynnnnnch, did you not try out your final build before publishing? : )

I did, then I published something that was not the final build.

**Comment by Rynchodon** [comment]
>Rynnnnnch, did you not try out your final build before publishing? : )

Of course I did, then I broke it.
GitHub isn't working, so I'll manually put the changes in.

**Comment by Rynchodon** [comment]
After b9a0b59723dadaf9c25999cff2156828f8783a72 I loaded up a world to make sure it compiled but I forgot that I had switched that world from local to steam version.

**Comment by zrisher** [comment]
Ahhhh yeah makes sense!

**Comment by N3X15** [comment]
I recommend testing by compiling the files with nant via Travis.  Continuous integration is pretty helpful.

**Comment by Rynchodon** [comment]
>I recommend testing by compiling the files with nant via Travis. Continuous integration is pretty helpful.

I have no idea what this sentence means.

**Comment by N3X15** [comment]
@Rynchodon [nant](http://nant.sourceforge.net/) is a command-line C# compiler.  You can also use msbuild, which will work with Visual Studio, as well.

[Travis](https://travis-ci.org/) is a Continuous Integration (CI) system, which compiles everything after you make a change to the repo and can run automated tests, if desired.  It's mostly used to just make sure that stuff compiles.  You could configure it to automatically deploy the project to Steam, for example.

**Pull request closed without merging**
